### ISSUE TITLE
Invalid MC_RUNTIME env var

### ISSUE THREAD

**Issue by FlorianVeaux** [hazelcast/management-center-docker#36]
Hi 👋 
Since https://github.com/hazelcast/management-center-docker/pull/35, the docker image tagged with "latest" is broken.
The specified `jar` file does not exist within the docker image, only the `war` one. Thus leading to the following error

```
+ exec java --add-opens java.base/java.lang=ALL-UNNAMED -server -Dhazelcast.mc.home=/data -Djava.net.preferIPv4Stack=true -XX:+UseContainerSupport -XX:MaxRAMPercentage=80 -cp /opt/hazelcast/management-center/hazelcast-management-center-4.0.3.jar -Dhazelcast.mc.contextPath=/ -Dhazelcast.mc.http.port=8080 -Dhazelcast.mc.https.port=8443 com.hazelcast.webmonitor.Launcher
Error: Could not find or load main class com.hazelcast.webmonitor.Launcher
Caused by: java.lang.ClassNotFoundException: com.hazelcast.webmonitor.Launcher
```

We have an automated CI that just failed because of this error, see [here](https://dev.azure.com/datadoghq/integrations-core/_build/results?buildId=20243&view=logs&jobId=8bfbe5b1-dfd9-5bd8-d33d-6a5f07468f09&j=8bfbe5b1-dfd9-5bd8-d33d-6a5f07468f09&t=6491cb3c-1a14-52fd-365b-728734cbb224)

### Reproduction steps:
`docker run hazelcast/management-center`

### Workaround

`docker run -e MC_RUNTIME=/opt/hazelcast/management-center/hazelcast-management-center-4.0.3.war hazelcast/management-center`

**Comment by erosb** [comment]
Hello @FlorianVeaux , thank you for reporting the problem. It will be fixed by #37 .
We changed the file extension from war to jar while preparing for the release upcoming this month (which will change the packaging to jar). We weren't aware of that the Dockerfile gets rebuilt and published after every merge, hence causing a broken image for the next few days. Sorry about the inconvenience.
